backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "proyek"
    label: "Proyek"
    files:
      - label: "Halaman Proyek 1"
        name: "proyek1"
        file: "proyek1.html"
        fields:
          - { label: "Konten", name: "body", widget: "markdown" }
